### ISSUE TITLE
unify SAMTOOLS_SORT_EXE vs SAMTOOLS_EXE and BAMUTIL vs BAM_EXE

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/gotcloud#26]
I want to just set `SAMTOOLS_SORT_EXE = $(SAMTOOLS_EXE)`.  This could cause problems, but I certainly hope not.

`BAMUTIL` is used only by `umake.pl`, for `clipOverlap`. `BAM_EXE` is used only by `align.pl` and some places in config-derived pipelines.  I could set `BAMUTIL = $(BAM_EXE)`, but that might cause problems.

**Comment by mktrost** [comment]
I guess the only catch with your proposed SAMTOOLS_SORT_EXE default is if someone only wanted to override SAMTOOLS_EXE, they'd have to know to also set SAMTOOLS_SORT_EXE to not point to SAMTOOLS_EXE.  That said, I think the current setting of SAMTOOLS_SORT_EXE independent of SAMTOOLS_EXE is more likely to cause problems if someone didn't realize they needed to override both settings to change the version of samtools.  Your proposed default would allow someone to change samtools for both by just putting SAMTOOLS_EXE in their config, so I think that is a good idea.

A little background: 
SAMTOOLS_SORT_EXE was created when samtools had a bug in its sort so a different version of samtools was required for sorting than everything else. Since that is fixed in the latest version of samtools, the same version of samtools can be used for both.  I think you are correct to default to SAMTOOLS_SORT_EXE = $(SAMTOOLS_EXE).  Or if you really wanted, you could deprecate SAMTOOLS_SORT_EXE, but that probably isn't necessary.

The different BAMUTIL & BAM_EXE was probably just due to the different authors of the original scripts that eventually became umake.pl and align.pl.  You could update it to use the same keyword for both, but then you'd want to handle older version of config files that have the older setting - you could either support both (like BAM_INDEX/BAM_LIST) or detect the deprecated setting and fail with a descriptive message (umake.pl has deprecatedDie to handle that type of thing).

Not sure if you were asking opinions or not, but I think your ideas are good.  
Really it is just the user needing to know that the tools are linked, so if they change one setting, the other will automatically changed.  I'd think in general that would be desired.
The current way requires users to realize they'd have to set multiple variables to change the version of the program used for all steps.  Your proposed way requires the user to realize if they don't want the version to change across the board they need to override the individual settings also.  I think in general a user would want to override all locations the program is used, so I think your proposal sounds better than the current implementation.

Sorry, for the long message, but I was just thinking through what the potential "problems" are and whether or not they are a real issue.

**Comment by pjvandehaar** [comment]
Thank you Mary Kate!  I was hoping to hear an experienced opinion on this, and what you said is very helpful.

What do you think of this plan:
- Make `umake.pl` use `BAM_EXE`.
- In `umake.pl`, `if(getConf("BAMUTIL")) { die if getconf("BAMUTIL") neq getConf("BAM_EXE") }`.

**Comment by mktrost** [comment]
Sorry for the delayed response.  I missed the email.  Yes, that plan sounds good.

**Comment by pjvandehaar** [comment]
Completed in commits https://github.com/statgen/gotcloud/commit/daca5d1ded83c4ddfaf5be7624352de983091edd and https://github.com/statgen/gotcloud/commit/c2cd31bfec65dfb8746e23e64f70cd04cf5cc05e .
